# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    deploy:

    needs: [build]
 runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password -> nama command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} -> Variable IP / host server kita
        username: ${{ secrets.USERNAME }} --> Variable Username server kita
        password: ${{ secrets.PASSWORD }} --> Variable Password server kita
        port: ${{ secrets.PORT }} --> Variable Port SSH server kita
        script: | -> Pipe
          cd /var/www/nomads --> lokasi file directory nodejs/ aplikasi kita
          ls -lah -> syntax / command yang kita jalankan 
